# Generated by Django 6.0.7 on 2026-07-26 05:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(max_length=20, unique=True, verbose_name='کد خدمت')),
                ('name', models.CharField(max_length=255, verbose_name='نام خدمت')),
                ('description', models.TextField(blank=True, verbose_name='شرح خدمت')),
                ('base_swu', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='واحد کار استاندارد پایه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'خدمت (کاتالوگ)',
                'verbose_name_plural': 'کاتالوگ خدمات',
                'ordering': ['service_code'],
            },
        ),
        migrations.CreateModel(
            name='WelfareYearlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='سال')),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='بودجه کل رفاهی')),
                ('reserved_fund', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='ذخیره موارد خاص')),
                ('distributable_budget', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18, verbose_name='بودجه قابل توزیع')),
                ('is_locked', models.BooleanField(default=False, help_text='پس از اجرای محاسبه توزیع، این بودجه قفل می\u200cشود.', verbose_name='قفل\u200cشده (پس از محاسبه نهایی)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'بودجه سالانه رفاهی',
                'verbose_name_plural': 'بودجه\u200cهای سالانه رفاهی',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('employee_code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='کد پرسنلی')),
                ('role', models.CharField(choices=[('EMPLOYEE', 'کارمند'), ('SUPERVISOR', 'سرپرست شهرستان'), ('PROVINCIAL_MANAGER', 'مدیر استانی'), ('ADMIN', 'کمیته ملی (ادمین)')], default='EMPLOYEE', max_length=20, verbose_name='نقش سازمانی')),
                ('region_code', models.CharField(db_index=True, max_length=20, verbose_name='کد منطقه/شهرستان')),
                ('province_code', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='کد استان')),
                ('region_coefficient', models.FloatField(default=1.0, help_text='ضریب ثابت منطقه که توسط کمیته ملی تعیین می\u200cشود.', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(3.0)], verbose_name='ضریب منطقه')),
                ('is_multitasking', models.BooleanField(default=False, verbose_name='چندوظیفه\u200cای')),
                ('multitasking_coefficient', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='ضریب چندوظیفگی')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='سمت سازمانی')),
                ('appointed_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انتصاب')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='سرپرست مستقیم')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
                'ordering': ['employee_code'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_performed', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاریخ انجام')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('base_swu_total', models.FloatField(default=0.0, editable=False, verbose_name='مجموع واحد کار پایه')),
                ('complexity_coefficient', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(3.0)], verbose_name='ضریب پیچیدگی درخواستی')),
                ('is_complexity_approved', models.BooleanField(default=False, verbose_name='ضریب پیچیدگی تایید شده')),
                ('adjusted_swu', models.FloatField(default=0.0, editable=False, verbose_name='واحد کار تعدیل\u200cشده')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار تایید'), ('APPROVED', 'تایید شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=10, verbose_name='وضعیت')),
                ('audit_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='امتیاز ممیزی کیفیت')),
                ('quality_coefficient', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(1.5)], verbose_name='ضریب کیفیت اعمال\u200cشده')),
                ('is_audit_selected', models.BooleanField(default=False, verbose_name='انتخاب\u200cشده برای ممیزی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_activities', to=settings.AUTH_USER_MODEL, verbose_name='تاییدکننده')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='کارمند')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='core.servicecatalog', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'فعالیت ثبت\u200cشده',
                'verbose_name_plural': 'فعالیت\u200cهای ثبت\u200cشده',
                'ordering': ['-date_performed', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='شرح وظیفه')),
                ('priority', models.CharField(choices=[('LOW', 'کم'), ('MEDIUM', 'متوسط'), ('HIGH', 'بالا')], default='MEDIUM', max_length=10, verbose_name='اولویت')),
                ('deadline', models.DateField(verbose_name='مهلت انجام')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('IN_PROGRESS', 'در حال انجام'), ('COMPLETED', 'تکمیل\u200cشده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=15, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL, verbose_name='محول\u200cکننده')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_received', to=settings.AUTH_USER_MODEL, verbose_name='مسئول انجام')),
                ('linked_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_task', to='core.activity', verbose_name='فعالیت ثبت\u200cشده مرتبط')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.servicecatalog', verbose_name='خدمت مرتبط')),
            ],
            options={
                'verbose_name': 'تخصیص وظیفه',
                'verbose_name_plural': 'تخصیص وظایف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WelfareDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='سال')),
                ('annual_adjusted_swu', models.FloatField(default=0.0, verbose_name='مجموع واحد کار تعدیل\u200cشده سالانه')),
                ('distribution_share', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='سهم محاسبه\u200cشده')),
                ('paid', models.BooleanField(default=False, verbose_name='پرداخت\u200cشده')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ محاسبه')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welfare_shares', to=settings.AUTH_USER_MODEL, verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'سهم توزیع رفاهی',
                'verbose_name_plural': 'سهم\u200cهای توزیع رفاهی',
                'ordering': ['-year', '-distribution_share'],
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['employee', 'date_performed'], name='core_activi_employe_75b082_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['status'], name='core_activi_status_aa6677_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='welfaredistribution',
            unique_together={('employee', 'year')},
        ),
    ]
