# Generated by Django 4.2.30 on 2026-07-29 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مناسبت/تعطیلی')),
                ('jalali_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='ماه (شمسی)')),
                ('jalali_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='روز (شمسی)')),
                ('jalali_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال شمسی (خالی = هرساله تکرار می\u200cشود)')),
                ('is_day_off', models.BooleanField(default=True, verbose_name='تعطیل رسمی (نه فقط مناسبت)')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'تعطیلات و مناسبت\u200cها',
                'verbose_name_plural': 'تعطیلات و مناسبت\u200cها',
                'ordering': ['jalali_month', 'jalali_day'],
                'unique_together': {('jalali_month', 'jalali_day', 'jalali_year')},
            },
        ),
    ]
